import '@fontsource/sora/latin-600.css';
import '@fontsource/sora/latin-700.css';
import { PublicClientApplication } from '@azure/msal-browser';
import './styles.css';
import { sampleCatalogue, type Catalogue, type Product, type QuoteRequest, type Settings } from './data';
import { money, parseCsv, requestsCsv } from './lib';

const app=document.querySelector<HTMLDivElement>('#app')!;
const API='/api';
const demoKey='demo:client-catalogue-request:requests';
const demoSubmittedKey='demo:client-catalogue-request:submitted';
const authKey='ccr:session';
const entra=new PublicClientApplication({auth:{clientId:'25c704f4-465a-47af-80ab-2c489466b697',authority:'https://sociobotcustomers.ciamlogin.com/35c6fe40-0ec0-46b6-98c6-213ad4de6650/',redirectUri:`${location.origin}/auth/callback`},cache:{cacheLocation:'sessionStorage'}});
const licenseKey='sb_license:client-catalogue-request';
const licenseCacheKey='sb_license_cache:client-catalogue-request';
const buildId=import.meta.env.VITE_BUILD_SHA||'dev';
let licenseNotice='';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));

function navigate(path:string){if(location.pathname.startsWith('/demo')&&!path.startsWith('/demo'))void discardDemo();history.pushState({},'',path);render();}
document.addEventListener('click',e=>{const a=(e.target as Element).closest<HTMLAnchorElement>('a[data-route]');if(a){e.preventDefault();navigate(a.pathname);}});
window.addEventListener('popstate',render);

function shell(content:string,nav=''){
  return `<a class="skip" href="#main">Skip to main content</a>
  ${nav}
  <header class="site-header"><a class="wordmark" href="/" data-route aria-label="Client Catalogue Request home"><span class="mark" aria-hidden="true"></span>Client Catalogue Request</a>
    <nav aria-label="Main navigation"><a href="/demo" data-route>Demo</a><a href="/manage" data-route>Seller workspace</a><a href="/privacy" data-route>Privacy</a></nav>
  </header>${content}
  <footer><p><strong>Client Catalogue Request</strong> turns private product lists into clear quote requests.</p><nav aria-label="Footer navigation"><a href="/privacy" data-route>Privacy</a><a href="/terms" data-route>Terms</a><a href="https://sociobot.in" rel="external">Built by Param Factory <span class="sr-only">(external site)</span></a></nav><p class="fine">Version 1.0 · Build ${esc(buildId.slice(0,12))} · Original generated artwork.</p></footer><div class="route-status sr-only" aria-live="polite"></div>`;
}

function setMeta(title:string,description:string){
  document.title=title;
  document.querySelector<HTMLMetaElement>('meta[name=description]')!.content=description;
  document.querySelector<HTMLLinkElement>('link[rel=canonical]')!.href=`https://client-catalogue-request.sociobot.in${location.pathname}`;
  requestAnimationFrame(()=>{const h1=document.querySelector<HTMLElement>('h1');if(h1)document.querySelector('.route-status')!.textContent=h1.textContent;});
}

function landing(){
  app.innerHTML=shell(`<main id="main">
    <section class="hero section-grid">
      <div class="hero-copy"><p class="eyebrow">Private catalogue · structured requests</p><h1>Turn repeat orders into clear requests</h1>
      <p class="lede">For small B2B sellers who need client orders without running an online store.</p>
      <div class="hero-action"><a class="button primary" href="/demo" data-route>Try it with sample data</a><span>Opens a private sample catalogue. No setup.</span></div>
      <ul class="fact-list"><li>No checkout or card data</li><li>Prices can stay POA</li><li>Client links are hard to guess</li></ul></div>
      <figure class="hero-art"><picture><source media="(max-width: 680px)" srcset="/assets/order-desk-720.webp"><img src="/assets/order-desk-1200.webp" width="1200" height="800" fetchpriority="high" alt="Glass product sheets flowing into one organized request document."></picture><figcaption>One private catalogue. One request you can use.</figcaption></figure>
    </section>
    <section class="live-strip ruled"><p class="index">01 / THE REQUEST LAYER</p><div><h2>Keep your catalogue. Lose the retyping.</h2><p>Import your product CSV. Share a protected link. Each client request arrives with SKUs, quantities, contact details, and notes.</p></div><div class="mini-request" aria-label="Example request"><span>RQ-6C24A19E</span><strong>Juniper Corner</strong><span>2 lines · PO-1842</span><b>Ready for CSV</b></div></section>
    <section class="steps ruled"><p class="index">02 / HOW IT WORKS</p><div><h2>From price list to usable request</h2><ol><li><span>1</span><div><h3>Import your CSV</h3><p>Keep SKU, name, price, category, and stock note fields. Leave price blank for POA.</p></div></li><li><span>2</span><div><h3>Share one client link</h3><p>Name each link for a client or group. The catalogue does not expose stock counts.</p></div></li><li><span>3</span><div><h3>Export each request</h3><p>Download the lines as CSV or print a clean request sheet to PDF.</p></div></li></ol></div></section>
    <section class="limits ruled"><p class="index">03 / CLEAR BOUNDARIES</p><div><h2>A request desk, not a storefront</h2><p>It does not take payments, promise stock, calculate shipping, or manage fulfillment. You review every request before quoting.</p><a href="/privacy" data-route>Read how request data is handled</a></div></section>
    <section class="pricing ruled"><p class="index">04 / PAID TIER</p><div><h2>Keep the free desk, or raise its limits</h2><p>The free workspace supports 12 catalogue rows and one client link. Request export stays free.</p></div><div class="price-block"><p><strong>₹1,499</strong> one-time</p><p>Use more than 12 catalogue rows and create more than one client link.</p><a class="button primary" href="https://api.sociobot.in/api/v1/products/client-catalogue-request/checkout">Buy the full workspace</a>${licenseForm('landing')}<p class="fine">Sociobot is the merchant of record. Refunds are handled there.</p></div></section>
  </main>`);
  wireLicenseForm('landing');
  setMeta('Client Catalogue Request — collect quote requests','Share a private product list and receive quote requests without running an online store.');
}

function demoBanner(){return `<aside class="demo-banner" aria-label="Demo mode"><strong>Demo — sample data, nothing is saved</strong><div><a href="/demo/inbox" data-route>Seller sample</a><button id="reset-demo">Reset demo</button><a href="/manage" data-route id="start-real">Start for real</a></div></aside>`;}

let basket=new Map<string,number>();
function cataloguePage(catalogue:Catalogue, demo:boolean, tokenValue=''){
  const categories=[...new Set(catalogue.products.map(p=>p.category))];
  app.innerHTML=shell(`<main id="main" class="catalogue-main">
    <section class="catalogue-head"><div><p class="eyebrow">Private client catalogue</p><h1>${esc(catalogue.settings.business_name)}</h1><p>${esc(catalogue.settings.price_label)} · ${esc(catalogue.settings.tax_note)}</p></div><button class="basket-button" id="open-basket">Review request <span id="basket-count">0</span></button></section>
    <section class="filter-shelf" aria-label="Catalogue filters"><label for="search">Search products</label><input id="search" type="search" placeholder="Name or SKU"><div class="chips"><button class="chip active" data-category="">All</button>${categories.map(c=>`<button class="chip" data-category="${esc(c)}">${esc(c)}</button>`).join('')}</div></section>
    <section aria-labelledby="products-title"><h2 id="products-title" class="sr-only">Products</h2><div id="products" class="product-landscape"></div><p id="no-products" class="empty hidden">${catalogue.products.length?'No products match this search. Clear the search or choose another category.':'This catalogue has no products yet. Ask the seller when it will be ready.'}</p></section>
    <dialog id="basket-dialog" aria-labelledby="basket-title"><form method="dialog" class="dialog-head"><h2 id="basket-title">Review your request</h2><button class="icon-button" aria-label="Close request">×</button></form><div id="basket-lines"></div><form id="request-form" class="request-form"><div class="form-grid"><label>Your name<input name="client_name" required minlength="2" maxlength="120" autocomplete="name"></label><label>Company<input name="company" required minlength="2" maxlength="120" autocomplete="organization"></label><label>Email<input name="email" required type="email" maxlength="254" autocomplete="email"></label><label>PO number <span>(optional)</span><input name="po_number" maxlength="80"></label></div><label>Request note <span>(optional)</span><textarea name="note" rows="3" maxlength="2000"></textarea></label><p class="fine">This sends a quote request. It does not place or pay for an order.</p><p id="form-error" class="error" role="alert"></p><button class="button primary" type="submit">Send quote request</button></form></dialog>
  </main>`,demo?demoBanner():'');
  let category='';
  const renderProducts=()=>{const q=(document.querySelector<HTMLInputElement>('#search')?.value||'').toLowerCase();const list=catalogue.products.filter(p=>(!category||p.category===category)&&(`${p.name} ${p.sku}`.toLowerCase().includes(q)));const box=document.querySelector('#products')!;box.innerHTML=list.map((p,i)=>productCard(p,catalogue.settings,i)).join('');document.querySelector('#no-products')!.classList.toggle('hidden',list.length>0);box.querySelectorAll<HTMLButtonElement>('[data-add]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.add!;basket.set(id,(basket.get(id)||0)+1);updateBasket();b.textContent='Added';setTimeout(()=>b.textContent='Add to request',700);}));};
  document.querySelector<HTMLInputElement>('#search')!.addEventListener('input',renderProducts);
  document.querySelectorAll<HTMLButtonElement>('[data-category]').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.category||'';document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts();}));
  const dialog=document.querySelector<HTMLDialogElement>('#basket-dialog')!;
  document.querySelector('#open-basket')!.addEventListener('click',()=>{renderBasket(catalogue);dialog.showModal();});
  document.querySelector('#request-form')!.addEventListener('submit',e=>submitRequest(e,catalogue,demo,tokenValue));
  if(demo){wireDemoBanner();}
  renderProducts(); updateBasket(); setMeta(`${demo?'Demo':'Catalogue'} — Client Catalogue Request`,demo?'Try a sample private catalogue and send a request without saving real data.':'Browse a private client catalogue and send a quote request.');
}

function productCard(p:Product,s:Settings,i:number){return `<article class="product-card"><div class="product-index">${String(i+1).padStart(2,'0')} · ${esc(p.category)}</div><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><dl><div><dt>SKU</dt><dd>${esc(p.sku)}</dd></div><div><dt>${esc(s.price_label)}</dt><dd>${money(p.price_cents,s.currency)}</dd></div></dl><p class="stock"><span aria-hidden="true">◌</span> ${esc(p.stock_note)}</p><button class="button secondary" data-add="${esc(p.id)}">Add to request</button></article>`;}
function updateBasket(){const count=[...basket.values()].reduce((a,b)=>a+b,0);const el=document.querySelector('#basket-count');if(el)el.textContent=String(count);}
function renderBasket(c:Catalogue){const box=document.querySelector('#basket-lines')!;if(!basket.size){box.innerHTML='<div class="empty"><h3>Your request is empty</h3><p>Add a product from the catalogue. It will appear here with its quantity.</p></div>';return;}box.innerHTML=[...basket].map(([id,qty])=>{const p=c.products.find(x=>x.id===id)!;return `<div class="basket-line"><div><strong>${esc(p.name)}</strong><span>${esc(p.sku)} · ${money(p.price_cents,c.settings.currency)}</span></div><label>Quantity<input type="number" min="1" max="9999" value="${qty}" data-qty="${esc(id)}"></label><button data-remove="${esc(id)}" aria-label="Remove ${esc(p.name)}">Remove</button></div>`;}).join('');box.querySelectorAll<HTMLInputElement>('[data-qty]').forEach(i=>i.addEventListener('change',()=>{basket.set(i.dataset.qty!,Math.max(1,Math.min(9999,Number(i.value)||1)));updateBasket();}));box.querySelectorAll<HTMLButtonElement>('[data-remove]').forEach(b=>b.addEventListener('click',()=>{basket.delete(b.dataset.remove!);renderBasket(c);updateBasket();}));}
async function submitRequest(e:Event,c:Catalogue,demo:boolean,tokenValue:string){e.preventDefault();const form=e.currentTarget as HTMLFormElement;const error=form.querySelector<HTMLElement>('#form-error')!;if(!basket.size){error.textContent='Your request is empty. Close this panel and add a product.';return;}const data=Object.fromEntries(new FormData(form));const payload={...data,lines:[...basket].map(([product_id,quantity])=>({product_id,quantity}))};const button=form.querySelector<HTMLButtonElement>('button[type=submit]')!;button.disabled=true;button.textContent='Sending request…';try{let id='';if(demo){const workspace=localStorage.getItem(demoKey);if(!workspace)throw new Error('The sample workspace is not available. Reset the demo and try again.');const res=await fetch(`${API}/demo/${encodeURIComponent(workspace)}/requests`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const body=await res.json();if(!res.ok)throw new Error(body.error);id=body.id;const submitted=JSON.parse(localStorage.getItem(demoSubmittedKey)||'[]') as QuoteRequest[];submitted.unshift(body.request);localStorage.setItem(demoSubmittedKey,JSON.stringify(submitted));}else{const res=await fetch(`${API}/requests/${encodeURIComponent(tokenValue)}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const body=await res.json();if(!res.ok)throw new Error(body.error);id=body.id;}const dialog=form.closest('dialog')!;dialog.innerHTML=`<div class="success"><span aria-hidden="true">✓</span><h2>Request ${esc(id)} received</h2><p>The seller can now review each product and quantity before sending a quote.</p><button id="new-request" class="button primary">Start another request</button></div>`;dialog.querySelector('#new-request')!.addEventListener('click',()=>location.reload());basket.clear();}catch(ex){error.textContent=ex instanceof Error?ex.message:'The request could not be sent. Check your connection and try again.';button.disabled=false;button.textContent='Send quote request';}}

async function loadClient(tokenValue:string){app.innerHTML=shell(`<main id="main"><section class="state-page"><div class="loader" aria-hidden="true"></div><h1>Opening your private catalogue</h1><p>Checking this client link now.</p></section></main>`);setMeta('Catalogue — Client Catalogue Request','Open a private client product catalogue.');try{const res=await fetch(`${API}/catalogue/${encodeURIComponent(tokenValue)}`);const body=await res.json();if(!res.ok)throw new Error(body.error);cataloguePage(body,false,tokenValue);}catch(ex){app.innerHTML=shell(`<main id="main"><section class="state-page"><p class="state-symbol" aria-hidden="true">×</p><h1>This catalogue is not available</h1><p>${esc(ex instanceof Error?ex.message:'The link could not be checked. Check your connection and reload this page.')}</p><button id="retry-client" class="button secondary">Try this link again</button></section></main>`);document.querySelector('#retry-client')!.addEventListener('click',()=>loadClient(tokenValue));setMeta('Catalogue unavailable — Client Catalogue Request','This private catalogue link is unavailable.');}}

function legal(kind:'privacy'|'terms'){
 const privacy=`<p class="eyebrow">Plain-language privacy notice</p><h1>Your request data stays with the seller</h1><p>Last updated 29 August 2026.</p><h2>What this service stores</h2><p>The seller stores catalogue data, protected client links, and quote requests. A request contains your name, company, email, PO number, note, products, and quantities.</p><h2>Why it is stored</h2><p>The seller uses it to prepare a quote or reorder. This service does not collect payment-card data or run advertising trackers.</p><h2>Demo and licenses</h2><p>The browser stores the sample workspace and any sample requests. The server does not retain demo requests. Reset demo removes that sample data from this browser. License tokens are stored in your browser and checked with the Sociobot billing service.</p><h2>Control your data</h2><p>Contact the seller who shared the client link to correct or delete a request. The seller can delete it from their inbox. You can clear browser storage to remove local session and license data.</p>`;
 const terms=`<p class="eyebrow">Terms of use</p><h1>Use requests as requests, not confirmed orders</h1><p>Last updated 28 August 2026.</p><h2>Service scope</h2><p>This service sends product requests to a seller. A request is not an accepted order, stock promise, shipping quote, or tax invoice.</p><h2>Your responsibilities</h2><p>Provide accurate contact and quantity details. Do not share a private client link outside its intended business group.</p><h2>Paid license</h2><p>The full workspace is a one-time purchase handled by Sociobot, the merchant of record. A refund revokes the related license. Core request exports remain available on the free tier.</p><h2>Availability</h2><p>The service is provided without a guarantee of uninterrupted access. Sellers should export important requests for their own records.</p>`;
 app.innerHTML=shell(`<main id="main"><article class="legal">${kind==='privacy'?privacy:terms}</article></main>`);setMeta(`${kind==='privacy'?'Privacy':'Terms'} — Client Catalogue Request`,kind==='privacy'?'How Client Catalogue Request stores catalogue, request, demo, and license data.':'Terms for sellers and clients using Client Catalogue Request.');
}

async function ensureDemo():Promise<string>{const current=localStorage.getItem(demoKey);if(current){const check=await fetch(`${API}/demo/${encodeURIComponent(current)}/requests`);if(check.ok)return current;localStorage.removeItem(demoKey);}const response=await fetch(`${API}/demo`,{method:'POST'});const body=await response.json();if(!response.ok)throw new Error(body.error||'The sample workspace could not open.');localStorage.setItem(demoKey,body.id);return body.id;}
async function discardDemo(){const current=localStorage.getItem(demoKey);localStorage.removeItem(demoKey);localStorage.removeItem(demoSubmittedKey);if(current)try{await fetch(`${API}/demo/${encodeURIComponent(current)}/requests`,{method:'DELETE'});}catch{/* The browser already discarded every sample request. */}}
function demoError(message:string){app.innerHTML=shell(`<main id="main"><section class="state-page"><p class="state-symbol" aria-hidden="true">!</p><h1>The sample workspace could not open</h1><p>${esc(message)}</p><button class="button secondary" id="retry-demo">Try the sample again</button></section></main>`,demoBanner());document.querySelector('#retry-demo')?.addEventListener('click',()=>void openDemo());wireDemoBanner();setMeta('Demo unavailable — Client Catalogue Request','The sample catalogue could not open.');}
async function openDemo(){app.innerHTML=shell(`<main id="main"><section class="state-page"><div class="loader" aria-hidden="true"></div><h1>Opening the sample catalogue</h1><p>Creating an isolated workspace now.</p></section></main>`,demoBanner());setMeta('Demo — Client Catalogue Request','Try a sample private catalogue and send a request without saving real data.');try{await ensureDemo();cataloguePage(sampleCatalogue,true,'demo');}catch(ex){demoError(ex instanceof Error?ex.message:'Check the server and try again.');}}
function wireDemoBanner(){document.querySelector('#reset-demo')?.addEventListener('click',async()=>{await discardDemo();basket.clear();await openDemo();});document.querySelector('#start-real')?.addEventListener('click',()=>void discardDemo());}
async function demoInbox(){try{const workspace=await ensureDemo();const response=await fetch(`${API}/demo/${encodeURIComponent(workspace)}/requests`);const body=await response.json();if(!response.ok)throw new Error(body.error);const submitted=JSON.parse(localStorage.getItem(demoSubmittedKey)||'[]') as QuoteRequest[];const requests=[...submitted,...body.requests as QuoteRequest[]];app.innerHTML=shell(`<main id="main" class="manage-main"><section class="manage-head"><div><p class="eyebrow">Sample seller inbox</p><h1>Use every line without retyping</h1><p>Northline Supply Co. · ${requests.length} sample ${requests.length===1?'request':'requests'}</p></div><a class="button secondary" href="/demo" data-route>Return to catalogue</a></section><section class="workspace-section"><div class="section-title"><div><p class="index">SAMPLE REQUESTS</p><h2>Requests arrive ready to export</h2></div><button id="demo-export" class="button primary">Export CSV</button></div><div class="request-list">${requests.map(r=>requestCard(r,sampleCatalogue.settings)).join('')}</div></section></main>`,demoBanner());document.querySelector('#demo-export')!.addEventListener('click',()=>download('sample-quote-requests.csv',requestsCsv(requests),'text/csv'));document.querySelectorAll<HTMLButtonElement>('[data-print]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.request-card').forEach(c=>c.classList.toggle('print-selected',c===b.closest('.request-card')));window.print();}));wireDemoBanner();setMeta('Demo seller inbox — Client Catalogue Request','Export structured sample requests as CSV or a print-ready request sheet.');}catch(ex){demoError(ex instanceof Error?ex.message:'Check the server and try again.');}}

function notFound(){app.innerHTML=shell(`<main id="main"><section class="not-found"><div class="lost-sheet" aria-hidden="true">404</div><h1>This request sheet went missing</h1><p>The address may be old or incomplete.</p><a class="button primary" href="/" data-route>Return to the start</a></section></main>`);setMeta('Page not found — Client Catalogue Request','The requested page could not be found.');}

function licenseForm(id:string){return `<form class="license-form" id="license-form-${id}"><label for="license-${id}">Have a license? Paste it<input id="license-${id}" name="license" autocomplete="off" spellcheck="false" required></label><button class="link-button" type="submit">Restore license</button><p class="license-notice fine" role="status">${esc(licenseNotice)}</p></form>`;}
function wireLicenseForm(id:string){const form=document.querySelector<HTMLFormElement>(`#license-form-${id}`);form?.addEventListener('submit',async event=>{event.preventDefault();const field=form.elements.namedItem('license') as HTMLInputElement;localStorage.setItem(licenseKey,field.value.trim());localStorage.removeItem(licenseCacheKey);const valid=await verifyLicense(true);licenseNotice=valid?'License saved. The server will check it when you raise a workspace limit.':'License no longer active. Check the token or buy the full workspace.';document.querySelectorAll<HTMLElement>('.license-notice').forEach(node=>node.textContent=licenseNotice);});}
async function verifyLicense(force=false):Promise<boolean>{const license=localStorage.getItem(licenseKey);if(!license)return false;const cache=JSON.parse(localStorage.getItem(licenseCacheKey)||'null');if(!force&&cache?.valid&&Date.now()-cache.checked<86400000)return true;try{const r=await fetch(`https://api.sociobot.in/api/v1/products/client-catalogue-request/verify?license=${encodeURIComponent(license)}`);const body=await r.json();const valid=!!body.valid;localStorage.setItem(licenseCacheKey,JSON.stringify({valid,checked:Date.now()}));if(!valid){licenseNotice='License no longer active. Check the token or buy the full workspace.';document.querySelectorAll<HTMLElement>('.license-notice').forEach(node=>node.textContent=licenseNotice);}return valid;}catch{return !!cache?.valid;}}

async function api<T>(path:string,options:RequestInit={}):Promise<T>{const headers=new Headers(options.headers);headers.set('content-type','application/json');const session=localStorage.getItem(authKey);if(session)headers.set('authorization',`Bearer ${session}`);const license=localStorage.getItem(licenseKey);if(license)headers.set('x-sociobot-license',license);const response=await fetch(`${API}${path}`,{...options,headers});const body=response.status===204?{}:await response.json();if(!response.ok){if(response.status===401)localStorage.removeItem(authKey);throw new Error(body.error||'The server could not finish that action.');}return body;}

async function accessToken(){const stored=localStorage.getItem(authKey);if(stored)return stored;const account=entra.getAllAccounts()[0];if(!account)return null;try{return (await entra.acquireTokenSilent({account,scopes:['openid','profile','email']})).accessToken;}catch{return null;}}
async function manage(){setMeta('Seller workspace — Client Catalogue Request','Import a catalogue, create private client links, and export incoming requests.');const token=await accessToken();if(!token){manageAuth();return;}localStorage.setItem(authKey,token);try{const [catalogue,requestData,paid]=await Promise.all([api<Catalogue>('/admin/catalogue'),api<{requests:QuoteRequest[]}>('/admin/requests'),verifyLicense()]);renderDashboard(catalogue,requestData.requests,paid);}catch(ex){manageState('The workspace could not open',ex instanceof Error?ex.message:'Try again.');}}
function manageState(title:string,message:string){app.innerHTML=shell(`<main id="main"><section class="state-page"><p class="state-symbol" aria-hidden="true">!</p><h1>${esc(title)}</h1><p>${esc(message)}</p><button class="button secondary" id="retry-manage">Try again</button></section></main>`);document.querySelector('#retry-manage')?.addEventListener('click',manage);}
function manageAuth(){app.innerHTML=shell(`<main id="main"><section class="auth-panel"><p class="eyebrow">Seller workspace</p><h1>Open your request desk</h1><p>Sign in with your Sociobot account. Your account gets its own private workspace.</p><button id="entra-signin" class="button primary">Sign in with Sociobot</button><p class="fine">Sign-in is provided by Sociobot Microsoft Entra External ID.</p></section></main>`);document.querySelector('#entra-signin')?.addEventListener('click',()=>void entra.loginRedirect({scopes:['openid','profile','email']}));}

function renderDashboard(catalogue:Catalogue,requests:QuoteRequest[],paid:boolean){
  const links=catalogue.links||[];
  app.innerHTML=shell(`<main id="main" class="manage-main"><section class="manage-head"><div><p class="eyebrow">Seller workspace</p><h1>Prepare links. Receive clean requests.</h1><p>${esc(catalogue.settings.business_name)} · ${catalogue.products.length} products · ${requests.length} requests</p></div><div class="license-state ${paid?'paid':''}">${paid?'Full workspace active':'Free workspace · 12 rows · 1 link'}</div></section>
  <nav class="workspace-tabs" aria-label="Workspace sections"><a href="#catalogue">Catalogue</a><a href="#links">Client links</a><a href="#requests">Requests</a></nav>
  <section id="catalogue" class="workspace-section"><div class="section-title"><div><p class="index">01 / CATALOGUE</p><h2>Import the list you already keep</h2></div><a href="/catalogue-template.csv" download>Download CSV template</a></div>
    <form id="catalogue-form"><div class="settings-grid"><label>Business name<input name="business_name" value="${esc(catalogue.settings.business_name)}" maxlength="80" required></label><label>Price label<input name="price_label" value="${esc(catalogue.settings.price_label)}" maxlength="40" required></label><label>Tax note<input name="tax_note" value="${esc(catalogue.settings.tax_note)}" maxlength="160"></label><label>Currency<input name="currency" value="${esc(catalogue.settings.currency)}" minlength="3" maxlength="3" required></label></div>
    <div class="drop-field"><label for="csv-file">Choose a product CSV</label><input id="csv-file" type="file" accept=".csv,text/csv"><p>Required: SKU and name. Optional: description, category, price, stock note.</p><p id="import-note" class="fine" role="status">Your current list has ${catalogue.products.length} rows.</p></div><p id="catalogue-error" class="error" role="alert"></p><button class="button primary" type="submit">Save catalogue</button></form>
    <div class="data-preview"><h3>Current product rows</h3>${catalogue.products.length?`<div class="table-wrap"><table><thead><tr><th>SKU</th><th>Product</th><th>Category</th><th>Price</th><th>Stock note</th></tr></thead><tbody>${catalogue.products.slice(0,20).map(p=>`<tr><td>${esc(p.sku)}</td><td>${esc(p.name)}</td><td>${esc(p.category)}</td><td>${money(p.price_cents,catalogue.settings.currency)}</td><td>${esc(p.stock_note)}</td></tr>`).join('')}</tbody></table></div>${catalogue.products.length>20?'<p class="fine">Showing the first 20 rows.</p>':''}`:'<div class="empty"><h3>No products yet</h3><p>Choose a CSV above. Its rows will appear here after you save.</p></div>'}</div>
  </section>
  <section id="links" class="workspace-section"><div class="section-title"><div><p class="index">02 / CLIENT LINKS</p><h2>Give each client a protected door</h2></div></div><form id="link-form" class="inline-form"><label>Client or group name<input name="label" required minlength="2" maxlength="120" placeholder="Juniper Corner"></label><button class="button secondary" type="submit">Create client link</button></form><p id="link-error" class="error" role="alert"></p><div class="link-list">${links.length?links.map(l=>`<div><span><strong>${esc(l.label)}</strong><small>${l.active?'Active':'Revoked'}</small></span>${l.active?`<a href="/c/${esc(l.token)}" target="_blank" rel="noopener">Open catalogue <span class="sr-only">for ${esc(l.label)} in a new tab</span></a><button data-copy="${location.origin}/c/${esc(l.token)}">Copy link</button><button data-revoke="${esc(l.token)}">Revoke link</button>`:'<small>This link can no longer open the catalogue.</small>'}</div>`).join(''):'<div class="empty"><h3>No client links yet</h3><p>Create a named link. Share it only with the intended client.</p></div>'}</div></section>
  <section id="requests" class="workspace-section"><div class="section-title"><div><p class="index">03 / REQUESTS</p><h2>Use every line without retyping</h2></div>${requests.length?'<button id="export-all" class="button secondary">Export CSV</button>':''}</div><div class="request-list">${requests.length?requests.map(r=>requestCard(r,catalogue.settings,true)).join(''):'<div class="empty"><h3>No requests yet</h3><p>A client request will appear here after they use a protected link.</p></div>'}</div></section>
  ${paid?'':`<section class="upgrade-panel"><p class="eyebrow">Full workspace</p><h2>Add more catalogue rows and client links</h2><p>₹1,499 one-time. Request export remains free.</p><div><a class="button primary" href="https://api.sociobot.in/api/v1/products/client-catalogue-request/checkout">Buy the full workspace</a>${licenseForm('manage')}</div></section>`}
  <section class="signout"><button id="sign-out" class="link-button">Sign out on this device</button></section></main>`);
  let pendingProducts=catalogue.products;
  const file=document.querySelector<HTMLInputElement>('#csv-file')!;file.addEventListener('change',async()=>{const note=document.querySelector('#import-note')!;try{if(!file.files?.[0])return;pendingProducts=parseCsv(await file.files[0].text());note.textContent=`Ready to save ${pendingProducts.length} product rows.`;}catch(ex){pendingProducts=catalogue.products;note.textContent=ex instanceof Error?ex.message:'The CSV could not be read.';}});
  document.querySelector<HTMLFormElement>('#catalogue-form')!.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget as HTMLFormElement;const error=form.querySelector<HTMLElement>('#catalogue-error')!;if(!paid&&pendingProducts.length>12){error.textContent='The free workspace accepts 12 rows. Buy the full workspace or import a shorter file.';return;}const fd=new FormData(form);const settings={business_name:String(fd.get('business_name')),price_label:String(fd.get('price_label')),tax_note:String(fd.get('tax_note')),currency:String(fd.get('currency'))};try{await api('/admin/catalogue',{method:'PUT',body:JSON.stringify({settings,products:pendingProducts})});await manage();}catch(ex){error.textContent=ex instanceof Error?ex.message:'The catalogue could not be saved.';}});
  document.querySelector<HTMLFormElement>('#link-form')!.addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget as HTMLFormElement;const error=document.querySelector<HTMLElement>('#link-error')!;if(!paid&&links.length>=1){error.textContent='The free workspace includes one client link. Buy the full workspace to create more.';return;}try{await api('/admin/links',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});await manage();}catch(ex){error.textContent=ex instanceof Error?ex.message:'The link could not be created.';}});
  document.querySelectorAll<HTMLButtonElement>('[data-copy]').forEach(b=>b.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(b.dataset.copy!);b.textContent='Copied';}catch{b.textContent='Copy failed — open the link';}}));
  document.querySelectorAll<HTMLButtonElement>('[data-revoke]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm('Revoke this client link? Anyone using it will lose access.'))return;try{await api(`/admin/links/${encodeURIComponent(b.dataset.revoke!)}/revoke`,{method:'POST'});await manage();}catch(ex){errorMessage('#link-error',ex);}}));
  document.querySelectorAll<HTMLButtonElement>('[data-delete-request]').forEach(b=>b.addEventListener('click',async()=>{if(!confirm(`Delete request ${b.dataset.deleteRequest}? This removes it from the seller inbox.`))return;try{await api(`/admin/requests/${encodeURIComponent(b.dataset.deleteRequest!)}`,{method:'DELETE'});await manage();}catch(ex){alert(ex instanceof Error?ex.message:'The request could not be deleted.');}}));
  document.querySelector('#export-all')?.addEventListener('click',()=>download('quote-requests.csv',requestsCsv(requests),'text/csv'));
  document.querySelectorAll<HTMLButtonElement>('[data-print]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.request-card').forEach(c=>c.classList.toggle('print-selected',c===b.closest('.request-card')));window.print();}));
  wireLicenseForm('manage');
  document.querySelector('#sign-out')?.addEventListener('click',()=>{localStorage.removeItem(authKey);manage();});
}
function errorMessage(selector:string,ex:unknown){const target=document.querySelector<HTMLElement>(selector);if(target)target.textContent=ex instanceof Error?ex.message:'The server could not finish that action.';}
function requestCard(r:QuoteRequest,s:Settings,manageable=false){return `<article class="request-card"><header><div><span>${esc(r.id)}</span><h3>${esc(r.company)}</h3><p>${esc(r.client_name)} · <a href="mailto:${esc(r.email)}">${esc(r.email)}</a></p></div><div><b>${esc(r.status)}</b><time>${esc(r.created_at)}</time></div></header><dl class="request-meta"><div><dt>PO number</dt><dd>${esc(r.po_number||'Not supplied')}</dd></div><div><dt>Client note</dt><dd>${esc(r.note||'No note')}</dd></div></dl><div class="table-wrap"><table><thead><tr><th>SKU</th><th>Product</th><th>Quantity</th><th>Unit price</th></tr></thead><tbody>${r.lines.map(l=>`<tr><td>${esc(l.sku)}</td><td>${esc(l.name)}</td><td>${l.quantity}</td><td>${money(l.price_cents,s.currency)}</td></tr>`).join('')}</tbody></table></div><button class="button secondary" data-print>Print request / save PDF</button>${manageable?`<button class="link-button danger-action" data-delete-request="${esc(r.id)}">Delete request</button>`:''}</article>`;}
function download(name:string,text:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}

function consumeLicense(){const p=new URLSearchParams(location.search);const value=p.get('license');if(value){localStorage.setItem(licenseKey,value);localStorage.removeItem(licenseCacheKey);p.delete('license');history.replaceState({},'',`${location.pathname}${p.size?'?'+p:''}`);void verifyLicense(true);}}

async function render(){consumeLicense();basket=new Map();const path=location.pathname;if(!path.startsWith('/demo')&&localStorage.getItem(demoKey))void discardDemo();if(path==='/')landing();else if(path==='/demo')await openDemo();else if(path==='/demo/inbox')await demoInbox();else if(path==='/privacy')legal('privacy');else if(path==='/terms')legal('terms');else if(path==='/manage'||path==='/auth/callback')await manage();else if(path.startsWith('/c/'))await loadClient(path.slice(3));else notFound();window.scrollTo({top:0,behavior:'instant'});}

void entra.initialize().then(()=>entra.handleRedirectPromise()).then(()=>render());
